### PR TITLE
Update Muxer.vb

### PR DESCRIPTION
**Pull request by wybb**
Add chapter cutting feature to MkvMuxer

### CODE REVIEW

**Comment by Revan654** [comment]
Been away for a bit, Has this been Tested? I don't like to add anything unless I know for sure it will work.

**Comment by wybb** [comment]
> Been away for a bit, Has this been Tested? I don't like to add anything unless I know for sure it will work.

Yes，It's work well. I have run this code many times. You can make a  simple test to check it.

**Comment by Revan654** [comment]
I have to manually add the code since, github tool keeps breaking.

I like to check, before adding any additional code that's not mine.

**Comment by Revan654** [comment]
Added the Merge to the Branch & Gave you credit in the Changelog.

**Comment by Revan654** [comment]
C:\Staxrip\General\Muxer.vb(563,28): error BC30451: 'XDocument' is not declared. It may be inaccessible due to its protection level. 
  C:\Staxrip\General\Muxer.vb(566,57): error BC30002: Type 'XElement' is not defined.

**Comment by Revan654** [comment]
You left out import System.Xml.Linq from the merge.

**Pull request merged**
